{% set name = "pyflowline" %}
{% set git_rev = "main" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/changliao1025/pyflowline

build:  
  noarch: python
  number: 1
  
requirements:  
  
  build:
    - python >=3.8    
    - setuptools
    - pip
  
  host:
    - python {{ python_min }}
    - pip
 
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - gdal
    - netCDF4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyflowline
  

about:
  home: https://github.com/changliao1025/pyflowline
  summary: A mesh-independent river network generator for hydrologic models.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - changliao1025
